name: Move enhancements card
on:
  issues:
    types:
      - opened
jobs:
  runs-on: ubuntu-latest
  if: contains( github.event.issues.labels.*.name, 'enhancement')
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: Enhancements
          column: New
          repo-token: ${{ secrets.PM_PERSONAL_ACCESS_TOKEN }}
